version: '2'
services:
  nginx:
   container_name: some-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 90:90
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   links:
   - api
   - app

  app:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    expose:
      - "8080"
    command: mvn clean spring-boot:run


  api:
    restart: always
    build: ./api
    working_dir: /api
    volumes:
    - ./api:/api
    expose:
    - "8090"
    command: mvn clean spring-boot:run

